### ISSUE TITLE
Update the version of nom

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/cds-moc-rust#5]
When compiling my code using moc it says:

warning: the following packages contain code that will be rejected by a future version of Rust: nom v6.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 546`

I saw with a cargo tree that moc relies on nom 6.1.2 which seems to be old. Is it possible to update its version to a more recent one ?

**Comment by fxpineau** [comment]
Done in 9a54267aa1c4e5aa1d4d4016d0390915221290d4
