### ISSUE TITLE
Ascii representation for empty STMOC is empty

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/cds-moc-rust#7]
We'd expect something like 

```
12/
t42/
```

for a STMOC with 12 and 42 max depths

**Comment by fxpineau** [comment]
You are right, thank you. The JSON serialization of an empty ST-MOC was also empty.
I added tests and fixed both (ASCII + JSON) serializations (+deserialization) in commit 78446e35da0f1e7635c0e236d40c8cac24d69f45.
