### ISSUE TITLE
accessing border_elementary_edges from storage

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/cds-moc-rust#9]
Hello FX, 
I would be nice if we could access https://docs.rs/moc/0.15.0/src/moc/moc/range/mod.rs.html#927 from storage for mocpy
Thanks

**Comment by fxpineau** [comment]
Done in commit https://github.com/cds-astro/cds-moc-rust/commit/4db65dd804bd3acf66eb6bde632b279df1b42e49.
